// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/upload.go
//
// Generated by this command:
//
//	mockgen -source=internal/interfaces/upload.go -destination=test/mocks/mock_upload.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	multipart "mime/multipart"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUploadProvider is a mock of UploadProvider interface.
type MockUploadProvider struct {
	ctrl     *gomock.Controller
	recorder *MockUploadProviderMockRecorder
	isgomock struct{}
}

// MockUploadProviderMockRecorder is the mock recorder for MockUploadProvider.
type MockUploadProviderMockRecorder struct {
	mock *MockUploadProvider
}

// NewMockUploadProvider creates a new mock instance.
func NewMockUploadProvider(ctrl *gomock.Controller) *MockUploadProvider {
	mock := &MockUploadProvider{ctrl: ctrl}
	mock.recorder = &MockUploadProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadProvider) EXPECT() *MockUploadProviderMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockUploadProvider) DeleteFile(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockUploadProviderMockRecorder) DeleteFile(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockUploadProvider)(nil).DeleteFile), path)
}

// UploadFile mocks base method.
func (m *MockUploadProvider) UploadFile(file *multipart.FileHeader, path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", file, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockUploadProviderMockRecorder) UploadFile(file, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockUploadProvider)(nil).UploadFile), file, path)
}
