// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/interfaces.go -destination=test/mocks/mock_services.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	multipart "mime/multipart"
	reflect "reflect"

	dto "github.com/kuldeepstechwork/gocart-api/internal/dto"
	utils "github.com/kuldeepstechwork/gocart-api/internal/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthServiceInterface is a mock of AuthServiceInterface interface.
type MockAuthServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockAuthServiceInterfaceMockRecorder is the mock recorder for MockAuthServiceInterface.
type MockAuthServiceInterfaceMockRecorder struct {
	mock *MockAuthServiceInterface
}

// NewMockAuthServiceInterface creates a new mock instance.
func NewMockAuthServiceInterface(ctrl *gomock.Controller) *MockAuthServiceInterface {
	mock := &MockAuthServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAuthServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceInterface) EXPECT() *MockAuthServiceInterfaceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthServiceInterface) Login(req *dto.LoginRequest) (*dto.AuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", req)
	ret0, _ := ret[0].(*dto.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceInterfaceMockRecorder) Login(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthServiceInterface)(nil).Login), req)
}

// Logout mocks base method.
func (m *MockAuthServiceInterface) Logout(refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceInterfaceMockRecorder) Logout(refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthServiceInterface)(nil).Logout), refreshToken)
}

// RefreshToken mocks base method.
func (m *MockAuthServiceInterface) RefreshToken(req *dto.RefreshTokenRequest) (*dto.AuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", req)
	ret0, _ := ret[0].(*dto.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockAuthServiceInterfaceMockRecorder) RefreshToken(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockAuthServiceInterface)(nil).RefreshToken), req)
}

// Register mocks base method.
func (m *MockAuthServiceInterface) Register(req *dto.RegisterRequest) (*dto.AuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", req)
	ret0, _ := ret[0].(*dto.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthServiceInterfaceMockRecorder) Register(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthServiceInterface)(nil).Register), req)
}

// MockUserServiceInterface is a mock of UserServiceInterface interface.
type MockUserServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockUserServiceInterfaceMockRecorder is the mock recorder for MockUserServiceInterface.
type MockUserServiceInterfaceMockRecorder struct {
	mock *MockUserServiceInterface
}

// NewMockUserServiceInterface creates a new mock instance.
func NewMockUserServiceInterface(ctrl *gomock.Controller) *MockUserServiceInterface {
	mock := &MockUserServiceInterface{ctrl: ctrl}
	mock.recorder = &MockUserServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceInterface) EXPECT() *MockUserServiceInterfaceMockRecorder {
	return m.recorder
}

// GetProfile mocks base method.
func (m *MockUserServiceInterface) GetProfile(userID uint) (*dto.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", userID)
	ret0, _ := ret[0].(*dto.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockUserServiceInterfaceMockRecorder) GetProfile(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockUserServiceInterface)(nil).GetProfile), userID)
}

// UpdateProfile mocks base method.
func (m *MockUserServiceInterface) UpdateProfile(userID uint, req *dto.UpdateProfileRequest) (*dto.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", userID, req)
	ret0, _ := ret[0].(*dto.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockUserServiceInterfaceMockRecorder) UpdateProfile(userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockUserServiceInterface)(nil).UpdateProfile), userID, req)
}

// MockProductServiceInterface is a mock of ProductServiceInterface interface.
type MockProductServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProductServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockProductServiceInterfaceMockRecorder is the mock recorder for MockProductServiceInterface.
type MockProductServiceInterfaceMockRecorder struct {
	mock *MockProductServiceInterface
}

// NewMockProductServiceInterface creates a new mock instance.
func NewMockProductServiceInterface(ctrl *gomock.Controller) *MockProductServiceInterface {
	mock := &MockProductServiceInterface{ctrl: ctrl}
	mock.recorder = &MockProductServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductServiceInterface) EXPECT() *MockProductServiceInterfaceMockRecorder {
	return m.recorder
}

// AddProductImage mocks base method.
func (m *MockProductServiceInterface) AddProductImage(productID uint, url, altText string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProductImage", productID, url, altText)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddProductImage indicates an expected call of AddProductImage.
func (mr *MockProductServiceInterfaceMockRecorder) AddProductImage(productID, url, altText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProductImage", reflect.TypeOf((*MockProductServiceInterface)(nil).AddProductImage), productID, url, altText)
}

// CreateCategory mocks base method.
func (m *MockProductServiceInterface) CreateCategory(req *dto.CreateCategoryRequest) (*dto.CategoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", req)
	ret0, _ := ret[0].(*dto.CategoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockProductServiceInterfaceMockRecorder) CreateCategory(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockProductServiceInterface)(nil).CreateCategory), req)
}

// CreateProduct mocks base method.
func (m *MockProductServiceInterface) CreateProduct(req *dto.CreateProductRequest) (*dto.ProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", req)
	ret0, _ := ret[0].(*dto.ProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockProductServiceInterfaceMockRecorder) CreateProduct(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockProductServiceInterface)(nil).CreateProduct), req)
}

// DeleteCategory mocks base method.
func (m *MockProductServiceInterface) DeleteCategory(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockProductServiceInterfaceMockRecorder) DeleteCategory(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockProductServiceInterface)(nil).DeleteCategory), id)
}

// DeleteProduct mocks base method.
func (m *MockProductServiceInterface) DeleteProduct(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockProductServiceInterfaceMockRecorder) DeleteProduct(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockProductServiceInterface)(nil).DeleteProduct), id)
}

// GetCategories mocks base method.
func (m *MockProductServiceInterface) GetCategories() ([]dto.CategoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategories")
	ret0, _ := ret[0].([]dto.CategoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategories indicates an expected call of GetCategories.
func (mr *MockProductServiceInterfaceMockRecorder) GetCategories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategories", reflect.TypeOf((*MockProductServiceInterface)(nil).GetCategories))
}

// GetProduct mocks base method.
func (m *MockProductServiceInterface) GetProduct(id uint) (*dto.ProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", id)
	ret0, _ := ret[0].(*dto.ProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockProductServiceInterfaceMockRecorder) GetProduct(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockProductServiceInterface)(nil).GetProduct), id)
}

// GetProducts mocks base method.
func (m *MockProductServiceInterface) GetProducts(page, limit int) ([]dto.ProductResponse, *utils.PaginationMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProducts", page, limit)
	ret0, _ := ret[0].([]dto.ProductResponse)
	ret1, _ := ret[1].(*utils.PaginationMeta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetProducts indicates an expected call of GetProducts.
func (mr *MockProductServiceInterfaceMockRecorder) GetProducts(page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProducts", reflect.TypeOf((*MockProductServiceInterface)(nil).GetProducts), page, limit)
}

// SearchProducts mocks base method.
func (m *MockProductServiceInterface) SearchProducts(req *dto.SearchProductsRequest) ([]dto.ProductSearchResult, *utils.PaginationMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchProducts", req)
	ret0, _ := ret[0].([]dto.ProductSearchResult)
	ret1, _ := ret[1].(*utils.PaginationMeta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchProducts indicates an expected call of SearchProducts.
func (mr *MockProductServiceInterfaceMockRecorder) SearchProducts(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchProducts", reflect.TypeOf((*MockProductServiceInterface)(nil).SearchProducts), req)
}

// UpdateCategory mocks base method.
func (m *MockProductServiceInterface) UpdateCategory(id uint, req *dto.UpdateCategoryRequest) (*dto.CategoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", id, req)
	ret0, _ := ret[0].(*dto.CategoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockProductServiceInterfaceMockRecorder) UpdateCategory(id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockProductServiceInterface)(nil).UpdateCategory), id, req)
}

// UpdateProduct mocks base method.
func (m *MockProductServiceInterface) UpdateProduct(id uint, req *dto.UpdateProductRequest) (*dto.ProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", id, req)
	ret0, _ := ret[0].(*dto.ProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockProductServiceInterfaceMockRecorder) UpdateProduct(id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockProductServiceInterface)(nil).UpdateProduct), id, req)
}

// MockCartServiceInterface is a mock of CartServiceInterface interface.
type MockCartServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCartServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockCartServiceInterfaceMockRecorder is the mock recorder for MockCartServiceInterface.
type MockCartServiceInterfaceMockRecorder struct {
	mock *MockCartServiceInterface
}

// NewMockCartServiceInterface creates a new mock instance.
func NewMockCartServiceInterface(ctrl *gomock.Controller) *MockCartServiceInterface {
	mock := &MockCartServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCartServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartServiceInterface) EXPECT() *MockCartServiceInterfaceMockRecorder {
	return m.recorder
}

// AddToCart mocks base method.
func (m *MockCartServiceInterface) AddToCart(userID uint, req *dto.AddToCartRequest) (*dto.CartResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToCart", userID, req)
	ret0, _ := ret[0].(*dto.CartResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddToCart indicates an expected call of AddToCart.
func (mr *MockCartServiceInterfaceMockRecorder) AddToCart(userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToCart", reflect.TypeOf((*MockCartServiceInterface)(nil).AddToCart), userID, req)
}

// GetCart mocks base method.
func (m *MockCartServiceInterface) GetCart(userID uint) (*dto.CartResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCart", userID)
	ret0, _ := ret[0].(*dto.CartResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCart indicates an expected call of GetCart.
func (mr *MockCartServiceInterfaceMockRecorder) GetCart(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCart", reflect.TypeOf((*MockCartServiceInterface)(nil).GetCart), userID)
}

// RemoveFromCart mocks base method.
func (m *MockCartServiceInterface) RemoveFromCart(userID, itemID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromCart", userID, itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromCart indicates an expected call of RemoveFromCart.
func (mr *MockCartServiceInterfaceMockRecorder) RemoveFromCart(userID, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromCart", reflect.TypeOf((*MockCartServiceInterface)(nil).RemoveFromCart), userID, itemID)
}

// UpdateCartItem mocks base method.
func (m *MockCartServiceInterface) UpdateCartItem(userID, itemID uint, req *dto.UpdateCartItemRequest) (*dto.CartResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartItem", userID, itemID, req)
	ret0, _ := ret[0].(*dto.CartResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCartItem indicates an expected call of UpdateCartItem.
func (mr *MockCartServiceInterfaceMockRecorder) UpdateCartItem(userID, itemID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartItem", reflect.TypeOf((*MockCartServiceInterface)(nil).UpdateCartItem), userID, itemID, req)
}

// MockOrderServiceInterface is a mock of OrderServiceInterface interface.
type MockOrderServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockOrderServiceInterfaceMockRecorder is the mock recorder for MockOrderServiceInterface.
type MockOrderServiceInterfaceMockRecorder struct {
	mock *MockOrderServiceInterface
}

// NewMockOrderServiceInterface creates a new mock instance.
func NewMockOrderServiceInterface(ctrl *gomock.Controller) *MockOrderServiceInterface {
	mock := &MockOrderServiceInterface{ctrl: ctrl}
	mock.recorder = &MockOrderServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderServiceInterface) EXPECT() *MockOrderServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockOrderServiceInterface) CreateOrder(userID uint) (*dto.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", userID)
	ret0, _ := ret[0].(*dto.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderServiceInterfaceMockRecorder) CreateOrder(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderServiceInterface)(nil).CreateOrder), userID)
}

// GetOrder mocks base method.
func (m *MockOrderServiceInterface) GetOrder(userID, orderID uint) (*dto.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", userID, orderID)
	ret0, _ := ret[0].(*dto.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockOrderServiceInterfaceMockRecorder) GetOrder(userID, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockOrderServiceInterface)(nil).GetOrder), userID, orderID)
}

// GetOrders mocks base method.
func (m *MockOrderServiceInterface) GetOrders(userID uint, page, limit int) ([]dto.OrderResponse, *utils.PaginationMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", userID, page, limit)
	ret0, _ := ret[0].([]dto.OrderResponse)
	ret1, _ := ret[1].(*utils.PaginationMeta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockOrderServiceInterfaceMockRecorder) GetOrders(userID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockOrderServiceInterface)(nil).GetOrders), userID, page, limit)
}

// MockUploadServiceInterface is a mock of UploadServiceInterface interface.
type MockUploadServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUploadServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockUploadServiceInterfaceMockRecorder is the mock recorder for MockUploadServiceInterface.
type MockUploadServiceInterfaceMockRecorder struct {
	mock *MockUploadServiceInterface
}

// NewMockUploadServiceInterface creates a new mock instance.
func NewMockUploadServiceInterface(ctrl *gomock.Controller) *MockUploadServiceInterface {
	mock := &MockUploadServiceInterface{ctrl: ctrl}
	mock.recorder = &MockUploadServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadServiceInterface) EXPECT() *MockUploadServiceInterfaceMockRecorder {
	return m.recorder
}

// UploadProductImage mocks base method.
func (m *MockUploadServiceInterface) UploadProductImage(productID uint, file *multipart.FileHeader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadProductImage", productID, file)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadProductImage indicates an expected call of UploadProductImage.
func (mr *MockUploadServiceInterfaceMockRecorder) UploadProductImage(productID, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadProductImage", reflect.TypeOf((*MockUploadServiceInterface)(nil).UploadProductImage), productID, file)
}
